name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Build
      working-directory: src
      run: dotnet build .\Elrondnet.sln  --configuration Release
      
    - name: Test
      working-directory: tests/Elrond-sdk.dotnet.tests
      run: dotnet test --no-build --verbosity normal
