name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Build with dotnet
      run: dotnet build Elrondnet.sln --configuration Release
      working-directory: src
      
    - name: Test
      working-directory: tests/Elrond-sdk.dotnet.tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish package
      working-directory: src
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
